# Generated by Django 2.2.3 on 2019-07-20 15:21
from decimal import Decimal

from django.db import migrations

LANGUAGES = ('en-gb', 'fr')

def create_orders(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for i, language in enumerate(LANGUAGES, 1):
        grand_total = Decimal('10.50') * i
        Order.objects.create(grand_total=grand_total, language=language)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_orders, migrations.RunPython.noop)
    ]
